name: Announcement

run-name: Send Announcement

on:
  schedule:
    # the time here is kinda random to dodge high load time on GH that may block cron jobs
    # if cron jobs are delayed for too long, they might be dropped -> bad
    - cron: '20 0 1 1 *'
    - cron: '20 0 29 1 *'

jobs:
  announce:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: 'Setup Deno'
        uses: denoland/setup-deno@v2

      - name: 'Send Announcement'
        run: |
          if [ "${{github.event.schedule}}" == '20 0 1 1 *' ]
          then
            message='The Census has reset! Renew your citizen status now: https://census.eisvana.com/renew.html'
          elif [ "${{github.event.schedule}}" == '20 0 29 1 *' ]
          then
            message='All <@&1178746333499240528> will lose the citizen role in 3 days. Renew your status now: https://census.eisvana.com/renew.html'
          fi

          if [ -n "$message" ]
          then
            deno run --allow-net ./.github/workflows/sendAnnouncement.ts ${{secrets.DISCORD_ANNOUNCEMENT_WEBHOOK}} "$message"
          fi
